[build]
publish = "public"
command = "pwd && cd themes/docsy && git submodule update -f --init && npm install postcss-cli && cd ../.. && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
GO_VERSION = "1.19"
HUGO_ENABLEGITINFO = "true"

